// This file was auto-generated by quicktype.

export interface Achievement {
    _id:          number;
    id:           string;
    name:         string;
    order:        number;
    achievements: AchievementElement[];
}

export interface AchievementElement {
    id:        number;
    name:      string;
    desc:      string;
    reward:    number;
    hidden:    boolean;
    order:     number;
    preStage?: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toAchievement(json: string): Achievement[] {
        return JSON.parse(json);
    }

    public static achievementToJson(value: Achievement[]): string {
        return JSON.stringify(value);
    }
}
