// This file was auto-generated by quicktype.

export interface Artifact {
    _id:        number;
    id:         string;
    name:       string;
    min_rarity: number;
    max_rarity: number;
    two_pc?:    string;
    four_pc?:   string;
    goblet?:    Circlet;
    plume?:     Circlet;
    circlet:    Circlet;
    flower?:    Circlet;
    sands?:     Circlet;
    one_pc?:    string;
}

export interface Circlet {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toArtifact(json: string): Artifact[] {
        return JSON.parse(json);
    }

    public static artifactToJson(value: Artifact[]): string {
        return JSON.stringify(value);
    }
}
