// This file was auto-generated by quicktype.

export interface Bait {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    craft:       Craft;
    fish:        Fish[];
}

export interface Craft {
    cost:   number;
    items:  Fish[];
    result: number;
}

export interface Fish {
    _id:     number;
    id:      string;
    name:    string;
    amount?: number;
    rarity?: number;
}
