// This file was auto-generated by quicktype.

export interface Bait {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    craft:       Craft;
    fish:        Fish[];
}

export interface Craft {
    items:  Fish[];
    result: number;
}

export interface Fish {
    _id:     number;
    id:      string;
    name:    string;
    amount?: number;
    rarity?: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toBait(json: string): Bait[] {
        return JSON.parse(json);
    }

    public static baitToJson(value: Bait[]): string {
        return JSON.stringify(value);
    }
}
