// This file was auto-generated by quicktype.

export interface CharacterExpMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    exp:         number;
}
