// This file was auto-generated by quicktype.

export interface CommonMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
    craft?:      Craft;
}

export interface Craft {
    cost:  number;
    items: Item[];
}

export interface Item {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toCommonMaterial(json: string): CommonMaterial[] {
        return JSON.parse(json);
    }

    public static commonMaterialToJson(value: CommonMaterial[]): string {
        return JSON.stringify(value);
    }
}
