// This file was auto-generated by quicktype.

export interface Domain {
    _id:                 number;
    id:                  string;
    name:                string;
    entranceId:          number;
    entranceName:        string;
    description:         string;
    regionId:            number;
    regionName:          string;
    recommendedLevel:    number;
    unlockRank:          number;
    disorder:            string[];
    filename_image:      string;
    recommendedElements: string[];
    domainType:          string;
    domainText:          string;
    rewardPreview:       RewardPreview[];
    monsterList:         MonsterList[];
}

export interface MonsterList {
    _id:  number;
    id:   string;
    name: string;
}

export interface RewardPreview {
    _id:     number;
    id:      string;
    name:    string;
    count?:  string;
    rarity?: number;
}
