// This file was auto-generated by quicktype.

export interface DomainsJSON {
    characters: Character[];
    weapons:    Character[];
}

export interface Character {
    domainName: string;
    rotation:   Rotation[];
}

export interface Rotation {
    day: string;
    ids: string[];
}
