// This file was auto-generated by quicktype.

export interface DomainsJSON {
    characters: Character[];
    weapons:    Character[];
}

export interface Character {
    domainName: string;
    rotation:   Rotation[];
}

export interface Rotation {
    day: string;
    ids: string[];
}

// Converts JSON strings to/from your types
export class Convert {
    public static toDomainsJSON(json: string): DomainsJSON[] {
        return JSON.parse(json);
    }

    public static domainsJSONToJson(value: DomainsJSON[]): string {
        return JSON.stringify(value);
    }
}
