// This file was auto-generated by quicktype.

export interface ElementalStoneMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toElementalStoneMaterial(json: string): ElementalStoneMaterial[] {
        return JSON.parse(json);
    }

    public static elementalStoneMaterialToJson(value: ElementalStoneMaterial[]): string {
        return JSON.stringify(value);
    }
}
