// This file was auto-generated by quicktype.

export interface ElementalStoneMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
}
