// This file was auto-generated by quicktype.

export interface Fish {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    source:      string[];
    bait?:       Bait;
}

export interface Bait {
    _id:    number;
    id:     string;
    name:   string;
    rarity: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toFish(json: string): Fish[] {
        return JSON.parse(json);
    }

    public static fishToJson(value: Fish[]): string {
        return JSON.stringify(value);
    }
}
