// This file was auto-generated by quicktype.

export interface FishingRod {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    source:      string[];
}
