// This file was auto-generated by quicktype.

export interface FishingRod {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    processing:  Processing[];
    source:      string[];
}

export interface Processing {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}
