// This file was auto-generated by quicktype.

export interface Fish {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    source:      string[];
    bait?:       Bait;
}

export interface Bait {
    _id:    number;
    id:     string;
    name:   string;
    rarity: number;
}
