// This file was auto-generated by quicktype.

export interface FishingRod {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    processing:  Processing[];
    source:      string[];
}

export interface Processing {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toFishingRod(json: string): FishingRod[] {
        return JSON.parse(json);
    }

    public static fishingRodToJson(value: FishingRod[]): string {
        return JSON.stringify(value);
    }
}
