// This file was auto-generated by quicktype.

export interface Food {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    ingredients: Ingredient[];
    dish_type:   string;
    results:     Results;
}

export interface Ingredient {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

export interface Results {
    suspicious: Delicious;
    normal:     Delicious;
    delicious:  Delicious;
    special?:   Special;
}

export interface Delicious {
    _id:         number;
    name:        string;
    description: string;
    effect:      string;
}

export interface Special {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    effect:      string;
    character:   Character;
}

export interface Character {
    id:   string;
    name: string;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toFood(json: string): Food[] {
        return JSON.parse(json);
    }

    public static foodToJson(value: Food[]): string {
        return JSON.stringify(value);
    }
}
