// This file was auto-generated by quicktype.

export interface Furnishing {
    _id:         number;
    id:          string;
    rarity:      number;
    name:        string;
    description: string;
    load:        number;
    energy:      number;
    category:    Category[];
    exp?:        number;
    recipe?:     Recipe[];
}

export interface Category {
    id:       number;
    category: string;
    type:     string;
}

export interface Recipe {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}
