// This file was auto-generated by quicktype.

export interface Geography {
    _id:               number;
    id:                string;
    name:              string;
    areaName?:         string;
    areaId:            number;
    description:       string;
    regionName:        string;
    regionId:          number;
    sortOrder:         number;
    filename_image:    string;
    showOnlyUnlocked?: boolean;
}
