// This file was auto-generated by quicktype.

export interface Ingredient {
    _id:          number;
    id:           string;
    name:         string;
    description?: string;
    recipes:      Craft[];
    source:       string[];
    processing?:  Craft[];
    craft?:       Craft[];
}

export interface Craft {
    id:      string;
    name:    string;
    amount?: number;
    _id?:    number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toIngredient(json: string): Ingredient[] {
        return JSON.parse(json);
    }

    public static ingredientToJson(value: Ingredient[]): string {
        return JSON.stringify(value);
    }
}
