// This file was auto-generated by quicktype.

export interface Ingredient {
    _id:          number;
    id:           string;
    name:         string;
    description?: string;
    recipes:      Craft[];
    source:       string[];
    rarity:       number;
    processing?:  Craft[];
    craft?:       Craft[];
}

export interface Craft {
    id:      string;
    name:    string;
    amount?: number;
    _id?:    number;
}
