// This file was auto-generated by quicktype.

export interface JewelMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
    craft?:      Craft;
    convert?:    Array<Convert[]>;
}

export interface Convert {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

export interface Craft {
    cost:   number;
    items:  Convert[];
    result: number;
}
