// This file was auto-generated by quicktype.

export interface JewelMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
    craft?:      Craft;
    convert?:    Array<Convert[]>;
}

export interface Convert {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

export interface Craft {
    cost:  number;
    items: Convert[];
}

// Converts JSON strings to/from your types
export class Convert {
    public static toJewelMaterial(json: string): JewelMaterial[] {
        return JSON.parse(json);
    }

    public static jewelMaterialToJson(value: JewelMaterial[]): string {
        return JSON.stringify(value);
    }
}
