// This file was auto-generated by quicktype.

export interface LocalMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    location?:   string;
    rarity?:     number;
}
