// This file was auto-generated by quicktype.

export interface Monster {
    _id:                         number;
    id:                          string;
    monsterId:                   number;
    name:                        string;
    specialNames:                Array<null | string>;
    rewardPreview:               RewardPreview[];
    monsterType:                 string;
    enemyType:                   string;
    categoryType:                string;
    categoryText:                string;
    filename_icon:               string;
    description:                 string;
    aggroRange:                  string;
    bgm:                         number;
    budget:                      number;
    stats:                       Stats;
    investigation?:              Investigation;
    filename_investigationIcon?: string;
    rewardPreviewId?:            number;
}

export interface Investigation {
    investigationId: number;
    name:            string;
    categoryType:    string;
    categoryText:    string;
    description:     string;
    lockdesc?:       string;
}

export interface RewardPreview {
    _id:     number;
    id:      string;
    name:    string;
    count?:  number;
    rarity?: number;
}

export interface Stats {
    resistance: Resistance;
    base:       Base;
    curve:      Curve;
}

export interface Base {
    hp:      number;
    attack:  number;
    defense: number;
}

export interface Curve {
    hp:      string;
    attack:  string;
    defense: string;
}

export interface Resistance {
    physical: number;
    pyro:     number;
    dendro:   number;
    hydro:    number;
    geo:      number;
    anemo:    number;
    cryo:     number;
    electro:  number;
}
