// This file was auto-generated by quicktype.

export interface Potion {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    effect:      string;
    craft:       Craft;
    rarity:      number;
}

export interface Craft {
    cost:  number;
    items: Item[];
}

export interface Item {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toPotion(json: string): Potion[] {
        return JSON.parse(json);
    }

    public static potionToJson(value: Potion[]): string {
        return JSON.stringify(value);
    }
}
