// This file was auto-generated by quicktype.

export interface Potion {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    effect:      string;
    craft:       Craft;
    rarity:      number;
}

export interface Craft {
    cost:   number;
    items:  Item[];
    result: number;
}

export interface Item {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}
