// This file was auto-generated by quicktype.

export interface TalentLvlUpMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
    convert?:    Array<Convert[]>;
    location?:   string;
    craft?:      Craft;
    domain?:     string;
    days?:       string[];
}

export interface Convert {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

export interface Craft {
    cost:  number;
    items: Convert[];
}

// Converts JSON strings to/from your types
export class Convert {
    public static toTalentLvlUpMaterial(json: string): TalentLvlUpMaterial[] {
        return JSON.parse(json);
    }

    public static talentLvlUpMaterialToJson(value: TalentLvlUpMaterial[]): string {
        return JSON.stringify(value);
    }
}
