// This file was auto-generated by quicktype.

export interface TalentLvlUpMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
    convert?:    Array<Convert[]>;
    location?:   string;
    craft?:      Craft;
    domain?:     string;
    domainId?:   string;
    days?:       string[];
}

export interface Convert {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

export interface Craft {
    cost:   number;
    items:  Convert[];
    result: number;
}
