// This file was auto-generated by quicktype.

export interface TcgAction {
    _id:                 number;
    id:                  string;
    shareId?:            number;
    name:                string;
    title:               string;
    desc:                string;
    in_play_description: string;
    attributes:          Attributes;
    skills:              Skill[];
}

export interface Attributes {
    cost:       number;
    cost_type?: string;
    card_type:  string;
    energy:     Energy[];
    source?:    string;
    tags?:      string[];
    food?:      Artifact;
    artifact?:  Artifact;
    faction?:   string[];
    character?: Character;
}

export interface Artifact {
    _id:    number;
    id:     string;
    name:   string;
    rarity: number;
}

export interface Character {
    id:   string;
    name: string;
}

export interface Energy {
    _id:   number;
    id:    string;
    type:  string;
    count: number;
}

export interface Skill {
    name: string;
    desc: string;
}
