// This file was auto-generated by quicktype.

export interface TcgMonster {
    _id:        number;
    id:         string;
    shareId:    number;
    name:       string;
    title:      null | string;
    desc:       null | string;
    attributes: Attributes;
    skills:     Skill[];
}

export interface Attributes {
    hp:           number;
    card_type:    string;
    energy:       number;
    element:      string;
    weapon:       string;
    faction:      string[];
    talent_card?: TalentCard;
    source:       null | string;
    character?:   Character;
}

export interface Character {
    id:   string;
    name: string;
}

export interface TalentCard {
    _id:  number;
    id:   string;
    name: string;
}

export interface Skill {
    id:       string;
    name:     string;
    desc:     string;
    skillTag: string[];
    points:   Point[];
}

export interface Point {
    _id:   number;
    id:    string;
    type:  string;
    count: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toTcgMonster(json: string): TcgMonster[] {
        return JSON.parse(json);
    }

    public static tcgMonsterToJson(value: TcgMonster[]): string {
        return JSON.stringify(value);
    }
}
