// This file was auto-generated by quicktype.

export interface TcgMonster {
    _id:        number;
    id:         string;
    shareId:    number;
    name:       string;
    title?:     string;
    desc:       string;
    attributes: Attributes;
    skills:     Skill[];
}

export interface Attributes {
    hp:           number;
    card_type:    string;
    energy:       number;
    faction:      null[];
    talent_card?: TalentCard;
    source?:      string;
    character?:   Character;
}

export interface Character {
    id:   string;
    name: string;
}

export interface TalentCard {
    _id:  number;
    id:   string;
    name: string;
}

export interface Skill {
    id:       string;
    name:     string;
    desc:     string;
    skillTag: any[];
    points:   Point[];
}

export interface Point {
    _id:   number;
    id:    string;
    type:  string;
    count: number;
}
