// This file was auto-generated by quicktype.

export interface WeaponSecondaryMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    rarity:      number;
    craft?:      Craft;
}

export interface Craft {
    cost:  number;
    items: Item[];
}

export interface Item {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toWeaponSecondaryMaterial(json: string): WeaponSecondaryMaterial[] {
        return JSON.parse(json);
    }

    public static weaponSecondaryMaterialToJson(value: WeaponSecondaryMaterial[]): string {
        return JSON.stringify(value);
    }
}
