// This file was auto-generated by quicktype.

export interface WeaponPrimaryMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    source:      string[];
    location:    string;
    rarity:      number;
    craft?:      Craft;
    domain:      string;
    days:        string[];
}

export interface Craft {
    cost:   number;
    items:  Item[];
    result: number;
}

export interface Item {
    _id:    number;
    id:     string;
    name:   string;
    amount: number;
}
