// This file was auto-generated by quicktype.

export interface WeaponEnhancementMaterial {
    _id:         number;
    id:          string;
    name:        string;
    description: string;
    rarity:      number;
    exp:         number;
}

// Converts JSON strings to/from your types
export class Convert {
    public static toWeaponEnhancementMaterial(json: string): WeaponEnhancementMaterial[] {
        return JSON.parse(json);
    }

    public static weaponEnhancementMaterialToJson(value: WeaponEnhancementMaterial[]): string {
        return JSON.stringify(value);
    }
}
